/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/streaming/pkg/apis/streaming/v1alpha1"
	scheme "knative.dev/streaming/pkg/client/clientset/versioned/scheme"
)

// InboundsGetter has a method to return a InboundInterface.
// A group's client should implement this interface.
type InboundsGetter interface {
	Inbounds(namespace string) InboundInterface
}

// InboundInterface has methods to work with Inbound resources.
type InboundInterface interface {
	Create(*v1alpha1.Inbound) (*v1alpha1.Inbound, error)
	Update(*v1alpha1.Inbound) (*v1alpha1.Inbound, error)
	UpdateStatus(*v1alpha1.Inbound) (*v1alpha1.Inbound, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Inbound, error)
	List(opts v1.ListOptions) (*v1alpha1.InboundList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Inbound, err error)
	InboundExpansion
}

// inbounds implements InboundInterface
type inbounds struct {
	client rest.Interface
	ns     string
}

// newInbounds returns a Inbounds
func newInbounds(c *StreamingV1alpha1Client, namespace string) *inbounds {
	return &inbounds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the inbound, and returns the corresponding inbound object, and an error if there is any.
func (c *inbounds) Get(name string, options v1.GetOptions) (result *v1alpha1.Inbound, err error) {
	result = &v1alpha1.Inbound{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inbounds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Inbounds that match those selectors.
func (c *inbounds) List(opts v1.ListOptions) (result *v1alpha1.InboundList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InboundList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inbounds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested inbounds.
func (c *inbounds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("inbounds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a inbound and creates it.  Returns the server's representation of the inbound, and an error, if there is any.
func (c *inbounds) Create(inbound *v1alpha1.Inbound) (result *v1alpha1.Inbound, err error) {
	result = &v1alpha1.Inbound{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("inbounds").
		Body(inbound).
		Do().
		Into(result)
	return
}

// Update takes the representation of a inbound and updates it. Returns the server's representation of the inbound, and an error, if there is any.
func (c *inbounds) Update(inbound *v1alpha1.Inbound) (result *v1alpha1.Inbound, err error) {
	result = &v1alpha1.Inbound{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inbounds").
		Name(inbound.Name).
		Body(inbound).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *inbounds) UpdateStatus(inbound *v1alpha1.Inbound) (result *v1alpha1.Inbound, err error) {
	result = &v1alpha1.Inbound{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inbounds").
		Name(inbound.Name).
		SubResource("status").
		Body(inbound).
		Do().
		Into(result)
	return
}

// Delete takes name of the inbound and deletes it. Returns an error if one occurs.
func (c *inbounds) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inbounds").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *inbounds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inbounds").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched inbound.
func (c *inbounds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Inbound, err error) {
	result = &v1alpha1.Inbound{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("inbounds").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
