/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	streamingv1alpha1 "knative.dev/streaming/pkg/apis/streaming/v1alpha1"
	versioned "knative.dev/streaming/pkg/client/clientset/versioned"
	internalinterfaces "knative.dev/streaming/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "knative.dev/streaming/pkg/client/listers/streaming/v1alpha1"
)

// StreamProcessorInformer provides access to a shared informer and lister for
// StreamProcessors.
type StreamProcessorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.StreamProcessorLister
}

type streamProcessorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStreamProcessorInformer constructs a new informer for StreamProcessor type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStreamProcessorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStreamProcessorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStreamProcessorInformer constructs a new informer for StreamProcessor type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStreamProcessorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StreamingV1alpha1().StreamProcessors(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StreamingV1alpha1().StreamProcessors(namespace).Watch(options)
			},
		},
		&streamingv1alpha1.StreamProcessor{},
		resyncPeriod,
		indexers,
	)
}

func (f *streamProcessorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStreamProcessorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *streamProcessorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&streamingv1alpha1.StreamProcessor{}, f.defaultInformer)
}

func (f *streamProcessorInformer) Lister() v1alpha1.StreamProcessorLister {
	return v1alpha1.NewStreamProcessorLister(f.Informer().GetIndexer())
}
